### ISSUE TITLE
Export Deleted Data is not working due to missing dependency EPPlus

### ISSUE THREAD

**Issue by LinnZawWin** [hieunguyen492/NNH.XrmToolBox.DeletedRecordRecovery#1]
I am getting the following error when I clicked Export Deleted Data
![image](https://user-images.githubusercontent.com/14156926/229502499-83c91069-cf88-47af-8243-920f53eb0586.png)

**Comment by hieunguyen492** [comment]
The error occurred because the third-party library EPPlus was used to export Excel but not merge to the main assembly file. It is now working after using the ILMerge tool to merge necessary assemblies. 
Please check the newest version.

**Comment by LinnZawWin** [comment]
Thanks, the Export Deleted Data button is now working in the latest version.
