### ISSUE TITLE
Filter User is not working properly when the whole word of the name is typed to filter

### ISSUE THREAD

**Issue by LinnZawWin** [hieunguyen492/NNH.XrmToolBox.DeletedRecordRecovery#2]
When I search with "nn", the list is filtered and shown properly.
![image](https://user-images.githubusercontent.com/14156926/229503132-3ca69321-0996-4611-ac1b-a85e9b895827.png)

But when I search with the whole word "Linn", the list is empty.
![image](https://user-images.githubusercontent.com/14156926/229503159-0fdbc151-7413-4904-ab63-9732026504e8.png)

Similarly, when I search with "aw", the list is filtered and shown properly.
![image](https://user-images.githubusercontent.com/14156926/229503303-adbd28d4-12f2-43cd-a32b-024477e482ef.png)

But when I search with the whole word "Zaw", the list is empty.
![image](https://user-images.githubusercontent.com/14156926/229503325-ccfc7554-1569-4528-9ff3-a6924aafef6c.png)

**Comment by hieunguyen492** [comment]
I have already fixed it by making the search function case-insensitive. 
Please check the newest version.

**Comment by LinnZawWin** [comment]
Thanks, it has been fixed.

![image](https://user-images.githubusercontent.com/14156926/231137003-b0b8e33a-dd0c-43f6-955f-ec53a69eb42e.png)
